"""empty message

Revision ID: 622133f75d4a
Revises: dd2c9b858c70
Create Date: 2020-09-09 13:03:02.152397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622133f75d4a'
down_revision = 'dd2c9b858c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_obra', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ponto', sa.Integer(), nullable=True),
    sa.Column('mira_superior', sa.Float(), nullable=True),
    sa.Column('mira_medio', sa.Float(), nullable=True),
    sa.Column('mira_inferior', sa.Float(), nullable=True),
    sa.Column('ang_vertical_g', sa.Float(), nullable=True),
    sa.Column('ang_vertical_m', sa.Float(), nullable=True),
    sa.Column('ang_vertical_s', sa.Float(), nullable=True),
    sa.Column('ang_horizontal_g', sa.Float(), nullable=True),
    sa.Column('ang_horizontal_m', sa.Float(), nullable=True),
    sa.Column('ang_horizontal_s', sa.Float(), nullable=True),
    sa.Column('dist_horizontal', sa.Float(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto')
    op.drop_table('obra')
    # ### end Alembic commands ###
